/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImageStudioRouteImport } from './routes/image-studio'
import { Route as PromptBuilderRouteImport } from './routes/prompt-builder'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageStudioRoute = ImageStudioRouteImport.update({
  id: '/image-studio',
  path: '/image-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptBuilderRoute = PromptBuilderRouteImport.update({
  id: '/prompt-builder',
  path: '/prompt-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/image-studio': typeof ImageStudioRoute
  '/prompt-builder': typeof PromptBuilderRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/image-studio': typeof ImageStudioRoute
  '/prompt-builder': typeof PromptBuilderRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/image-studio': typeof ImageStudioRoute
  '/prompt-builder': typeof PromptBuilderRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/image-studio' | '/prompt-builder' | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/image-studio' | '/prompt-builder' | '/api/chat'
  id: '__root__' | '/' | '/image-studio' | '/prompt-builder' | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImageStudioRoute: typeof ImageStudioRoute
  PromptBuilderRoute: typeof PromptBuilderRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-studio': {
      id: '/image-studio'
      path: '/image-studio'
      fullPath: '/image-studio'
      preLoaderRoute: typeof ImageStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-builder': {
      id: '/prompt-builder'
      path: '/prompt-builder'
      fullPath: '/prompt-builder'
      preLoaderRoute: typeof PromptBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImageStudioRoute: ImageStudioRoute,
  PromptBuilderRoute: PromptBuilderRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
